# docker-compose-base.yml
version: "3"
services:
  service_nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./html:/usr/share/nginx/html/xxx-ui
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=tingyur.top
      - NGINX_PORT=80

  service_redis:
    image: redis
    ports:
      - "6379:6379"

  # tomcat:
  #   image: tomcat
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - service_nacos
  #     - service_redis

  service_nacos:
    image: nacos/nacos-server:2.0.0-bugfix
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=service_mysql
      - MYSQL_SERVICE_DB_NAME=xxx-config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=a123456
    volumes:
      - ./nacos/log/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    depends_on:
      - service_mysql
    restart: on-failure

  service_mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=a123456
    volumes:
      - ./mysql/init.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    restart: on-failure
