# docker-compose-service.yml
version: "3"
services:
  service_reactcases_ssr:
    hostname: service_reactcases_ssr
    container_name: service_reactcases_ssr
    build: ./services/reactcases_ssr
    image: reactcases-ssr:1.0
    volumes:
      - ./ssr_html:/usr/src/reactcases/ssr_html
    ports:
      - "7001:7001"
    networks:
      - web_common

networks:
  web_common:
    external: true
